version: '3'
services:
        dev:
                build: .
                command: sh -c "yarn && yarn start"
                ports:
                        - "80:3000"
                working_dir: /app
                volumes:
                        - .:/app:cached
